// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJmrqLf6pGQCcOLadtzSNQ7n6y6GEoikU',
    appId: '1:594574082502:web:5dabbb59f99d1fc9a132c7',
    messagingSenderId: '594574082502',
    projectId: 'tickbook-c0a4e',
    authDomain: 'tickbook-c0a4e.firebaseapp.com',
    storageBucket: 'tickbook-c0a4e.firebasestorage.app',
    measurementId: 'G-CPZN90865P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWy3V2mT6oW7hUtgfWXP9CCGNYSsN3NM',
    appId: '1:594574082502:android:660b76eafccb3475a132c7',
    messagingSenderId: '594574082502',
    projectId: 'tickbook-c0a4e',
    storageBucket: 'tickbook-c0a4e.firebasestorage.app',
  );
}
